###############################################################################
#                                                                             #
#                           Fishing Out Nutrients                             #
#     Comparisons Between Study Estimates and Uniform Value Estimates         #
#                                                                             #
###############################################################################


# This script compared our estimates to the estimates generated by using uniform averages as had been done in previous publications. Uniform values were defined as follows: C = 12.5% (Mariani et al. 2020), N = 2.8% (Le Mezo et al. 2022), and P = 0.6% (Le Mezo et al. 2022). All values calculated using these uniform (global) values are prefaced with "GloAv".



#### NECESSARY PACKAGES ####

library(tidyverse)
library(data.table)
library(GGally)
library(nlme)
library(lme4)
library (MuMIn)
library(ggpubr)
library(mvtnorm)
library(ggplot2)
library(reshape2)
library(ggrepel)
library(treemapify)





#### PER YEAR ####
GloAv_NutrientExtraction_perYear <- Fisheries_NutrientExtraction %>% 
  group_by(year) %>% 
  summarize(GloAv_C_extracted = sum(tonnes * 0.125, na.rm = TRUE), 
            GloAv_N_extracted = sum(tonnes * 0.028, na.rm = TRUE), 
            GloAv_P_extracted = sum(tonnes * 0.006, na.rm = TRUE))

# Merges our estimates to those produced using the uniform values.
GloAv_NutrientExtraction_perYear <- merge(NutrientExtraction_perYear, GloAv_NutrientExtraction_perYear, by = "year",all.x = TRUE)

# Calculates difference between using uniform estimates (GloAv values) and our extraction estimates. Positive numbers indicate overestimates by uniform estimates, negative numbers indicate underestimations. Relative percentage difference between our estimates and the uniform estimates was also calculated.

GloAv_NutrientExtraction_perYear <- GloAv_NutrientExtraction_perYear %>% 
  mutate(
    # Carbon
    C_dif = GloAv_C_extracted - C_extracted,
         C_dif_SD = C_extracted_SD,
         C_dif_lowCI = GloAv_C_extracted - C_extracted_highCI,
         C_dif_highCI = GloAv_C_extracted - C_extracted_lowCI,
         C_dif_per = (C_dif / C_extracted) * 100,
         C_dif_per_SD = abs((sqrt((C_dif_SD / C_dif)^2 + (C_extracted_SD/C_extracted)^2))*C_dif_per),
         C_dif_per_lowCI = (C_dif_lowCI / C_extracted_highCI) * 100,
         C_dif_per_highCI = (C_dif_highCI / C_extracted_lowCI) * 100,
         # Nitrogen
         N_dif = GloAv_N_extracted - N_extracted,
         N_dif_SD = N_extracted_SD,
         N_dif_lowCI = GloAv_N_extracted - N_extracted_highCI,
         N_dif_highCI = GloAv_N_extracted - N_extracted_lowCI,
         N_dif_per = (N_dif / N_extracted) * 100,
         N_dif_per_SD = abs((sqrt((N_dif_SD / N_dif)^2 + (N_extracted_SD/N_extracted)^2))*N_dif_per),
         N_dif_per_lowCI = (N_dif_lowCI / N_extracted_highCI) * 100,
         N_dif_per_highCI = (N_dif_highCI / N_extracted_lowCI) * 100,
         # Phosphorus
         P_dif = GloAv_P_extracted - P_extracted,
         P_dif_SD = P_extracted_SD,
         P_dif_lowCI = GloAv_P_extracted - P_extracted_highCI,
         P_dif_highCI = GloAv_P_extracted - P_extracted_lowCI,
         P_dif_per = (P_dif / P_extracted) * 100,
         P_dif_per_SD = abs((sqrt((P_dif_SD / P_dif)^2 + (P_extracted_SD/P_extracted)^2))*P_dif_per),
         P_dif_per_lowCI = (P_dif_lowCI / P_extracted_highCI) * 100,
         P_dif_per_highCI = (P_dif_highCI / P_extracted_lowCI) * 100)






#### PER MARINE REGION ####

# The following code is to produce the uniform estimates per marine region.

GloAv_NutrientExtraction_perArea <- Fisheries_NutrientExtraction %>% group_by(area_name) %>%
  filter(year %in% c(1960:2018)) %>% 
  summarize(GloAv_C_extracted = sum(tonnes * 0.125, na.rm = TRUE),
            GloAv_C_1960_64 = sum(ifelse(between(year, 1960, 1964),tonnes * 0.125, 0), na.rm = TRUE),
            GloAv_C_1993_97 = sum(ifelse(between(year, 1993, 1997),tonnes * 0.125, 0), na.rm = TRUE),
            GloAv_C_2014_18 = sum(ifelse(between(year, 2014, 2018),tonnes * 0.125, 0), na.rm = TRUE),
            GloAv_N_extracted = sum(tonnes * 0.028, na.rm = TRUE), 
            GloAv_N_1960_64 = sum(ifelse(between(year, 1960, 1964),tonnes * 0.028, 0), na.rm = TRUE), 
            GloAv_N_1993_97 = sum(ifelse(between(year, 1993, 1997),tonnes * 0.028, 0), na.rm = TRUE), 
            GloAv_N_2014_18 = sum(ifelse(between(year, 2014, 2018),tonnes * 0.028, 0), na.rm = TRUE), 
            GloAv_P_extracted = sum(tonnes * 0.006, na.rm = TRUE),
            GloAv_P_1960_64 = sum(ifelse(between(year, 1960, 1964),tonnes * 0.006, 0), na.rm = TRUE),
            GloAv_P_1993_97 = sum(ifelse(between(year, 1993, 1997),tonnes * 0.006, 0), na.rm = TRUE),
            GloAv_P_2014_18 = sum(ifelse(between(year, 2014, 2018),tonnes * 0.006, 0), na.rm = TRUE))


# Per SqKm calculations for uniform estimates.
GloAv_NutrientExtraction_perArea <- GloAv_NutrientExtraction_perArea %>%
  mutate(GloAv_C_perSqKm = GloAv_C_extracted/area_km2,
         GloAv_N_perSqKm = GloAv_N_extracted/area_km2,
         GloAv_P_perSqKm = GloAv_P_extracted/area_km2) %>% 
  
  # Percent difference
  mutate(C_perSqKm_dif = GloAv_C_perSqKm - C_extracted_perSqKm,
         C_perSqKm_dif_SD = C_extracted_perSqKm_SD,
         C_perSqKm_dif_per = (C_perSqKm_dif / C_extracted_perSqKm) * 100,
         C_perSqKm_dif_per_SD = 
           abs(sqrt((C_perSqKm_dif_SD / C_perSqKm_dif)^2 + 
                      (C_extracted_perSqKm_SD/C_extracted_perSqKm)^2) * C_perSqKm_dif_per),
         # Nitrogen
         N_perSqKm_dif = GloAv_N_perSqKm - N_extracted_perSqKm,
         N_perSqKm_dif_SD = N_extracted_perSqKm_SD,
         N_perSqKm_dif_per = (N_perSqKm_dif / N_extracted_perSqKm) * 100,
         N_perSqKm_dif_per_SD = 
           abs(sqrt((N_perSqKm_dif_SD / N_perSqKm_dif)^2 + 
                      (N_extracted_perSqKm_SD/N_extracted_perSqKm)^2) * N_perSqKm_dif_per),
         # Phosphorus
         P_perSqKm_dif = GloAv_P_perSqKm - P_extracted_perSqKm,
         P_perSqKm_dif_SD = P_extracted_perSqKm_SD,
         P_perSqKm_dif_per = (P_perSqKm_dif / P_extracted_perSqKm) * 100,
         P_perSqKm_dif_per_SD = 
           abs(sqrt((P_perSqKm_dif_SD / P_perSqKm_dif)^2 + 
                      (P_extracted_perSqKm_SD/P_extracted_perSqKm)^2) * P_perSqKm_dif_per))






#### PER TROPHIC GROUP ####

# The following code is to produce the global estimates per trophic group.

GloAv_NutrientExtraction_perTG <- Fisheries_NutrientExtraction %>% group_by(trophic_group) %>%
  filter(year %in% c(1960:2018)) %>% 
  summarize(GloAv_C_extracted = sum(tonnes * 0.125, na.rm = TRUE),
            GloAv_C_1960_64 = sum(ifelse(between(year, 1960, 1964),tonnes * 0.125, 0), na.rm = TRUE),
            GloAv_C_1993_97 = sum(ifelse(between(year, 1993, 1997),tonnes * 0.125, 0), na.rm = TRUE),
            GloAv_C_2014_18 = sum(ifelse(between(year, 2014, 2018),tonnes * 0.125, 0), na.rm = TRUE),
            GloAv_N_extracted = sum(tonnes * 0.028, na.rm = TRUE), 
            GloAv_N_1960_64 = sum(ifelse(between(year, 1960, 1964),tonnes * 0.028, 0), na.rm = TRUE), 
            GloAv_N_1993_97 = sum(ifelse(between(year, 1993, 1997),tonnes * 0.028, 0), na.rm = TRUE), 
            GloAv_N_2014_18 = sum(ifelse(between(year, 2014, 2018),tonnes * 0.028, 0), na.rm = TRUE), 
            GloAv_P_extracted = sum(tonnes * 0.006, na.rm = TRUE),
            GloAv_P_1960_64 = sum(ifelse(between(year, 1960, 1964),tonnes * 0.006, 0), na.rm = TRUE),
            GloAv_P_1993_97 = sum(ifelse(between(year, 1993, 1997),tonnes * 0.006, 0), na.rm = TRUE),
            GloAv_P_2014_18 = sum(ifelse(between(year, 2014, 2018),tonnes * 0.006, 0), na.rm = TRUE))

GloAv_NutrientExtraction_perTG <- merge(NutrientExtraction_perTG, GloAv_NutrientExtraction_perTG, by = "trophic_group",all.x = TRUE)
# Calculate difference between using global averages and our composition estimates. Positive numbers indicate overestimates by global averages, negative numbers indicate underestimates
GloAv_NutrientExtraction_perTG <- GloAv_NutrientExtraction_perTG %>% 
  #Carbon
  mutate(C_dif = GloAv_C_extracted - C_extracted,
         C_dif_SD = C_extracted_SD,
         C_dif_lowCI = GloAv_C_extracted - C_extracted_highCI,
         C_dif_highCI = GloAv_C_extracted - C_extracted_lowCI,
         C_dif_per = (C_dif / C_extracted) * 100,
         C_dif_per_SD = abs(sqrt((C_dif_SD / C_dif)^2 + (C_extracted_SD/C_extracted)^2) * C_dif_per),
         C_dif_per_lowCI = (C_dif_lowCI / C_extracted_highCI) * 100,
         C_dif_per_highCI = (C_dif_highCI / C_extracted_lowCI) * 100,
         
         C_dif_1960_64 = GloAv_C_1960_64 - C_extracted_1960_64,
         C_dif_1960_64_SD = C_extracted_SD_1960_64,
         C_dif_1960_64_lowCI = GloAv_C_1960_64 - C_extracted_highCI_1960_64,
         C_dif_1960_64_highCI = GloAv_C_1960_64 - C_extracted_lowCI_1960_64,
         C_dif_1960_64_per = (C_dif_1960_64 / C_extracted_1960_64) * 100,
         C_dif_1960_64_per_SD = abs(sqrt((C_dif_1960_64_SD / C_dif_1960_64)^2 + (C_extracted_SD_1960_64/C_extracted_1960_64)^2) * C_dif_1960_64_per),
         C_dif_1960_64_per_lowCI = (C_dif_1960_64_lowCI / C_extracted_highCI_1960_64) * 100,
         C_dif_1960_64_per_highCI = (C_dif_1960_64_highCI / C_extracted_lowCI_1960_64) * 100,
         
         C_dif_1993_97 = GloAv_C_1993_97 - C_extracted_1993_97,
         C_dif_1993_97_SD = C_extracted_SD_1993_97,
         C_dif_1993_97_lowCI = GloAv_C_1993_97 - C_extracted_highCI_1993_97,
         C_dif_1993_97_highCI = GloAv_C_1993_97 - C_extracted_lowCI_1993_97,
         C_dif_1993_97_per = (C_dif_1993_97 / C_extracted_1993_97) * 100,
         C_dif_1993_97_per_SD = abs(sqrt((C_dif_1993_97_SD / C_dif_1993_97)^2 + (C_extracted_SD_1993_97 / C_extracted_1993_97)^2) * C_dif_1993_97_per),
         C_dif_1993_97_per_lowCI = (C_dif_1993_97_lowCI / C_extracted_highCI_1993_97) * 100,
         C_dif_1993_97_per_highCI = (C_dif_1993_97_highCI / C_extracted_lowCI_1993_97) * 100,
         
         C_dif_2014_18 = GloAv_C_2014_18 - C_extracted_2014_18,
         C_dif_2014_18_SD = C_extracted_SD_2014_18,
         C_dif_2014_18_lowCI = GloAv_C_2014_18 - C_extracted_highCI_2014_18,
         C_dif_2014_18_highCI = GloAv_C_2014_18 - C_extracted_lowCI_2014_18,
         C_dif_2014_18_per = (C_dif_2014_18 / C_extracted_2014_18) * 100,
         C_dif_2014_18_per_SD = abs(sqrt((C_dif_2014_18_SD / C_dif_2014_18)^2 + (C_extracted_SD_2014_18 / C_extracted_2014_18)^2) * C_dif_2014_18_per),
         C_dif_2014_18_per_lowCI = (C_dif_2014_18_lowCI / C_extracted_highCI_2014_18) * 100,
         C_dif_2014_18_per_highCI = (C_dif_2014_18_highCI / C_extracted_lowCI_2014_18) * 100) %>% 
  #Nitrogen
  mutate(N_dif = GloAv_N_extracted - N_extracted,
         N_dif_SD = N_extracted_SD,
         N_dif_lowCI = GloAv_N_extracted - N_extracted_highCI,
         N_dif_highCI = GloAv_N_extracted - N_extracted_lowCI,
         N_dif_per = (N_dif / N_extracted) * 100,
         N_dif_per_SD = abs(sqrt((N_dif_SD / N_dif)^2 + (N_extracted_SD / N_extracted)^2) * N_dif_per),
         N_dif_per_lowCI = (N_dif_lowCI / N_extracted_highCI) * 100,
         N_dif_per_highCI = (N_dif_highCI / N_extracted_lowCI) * 100,
         
         N_dif_1960_64 = GloAv_N_1960_64 - N_extracted_1960_64,
         N_dif_1960_64_SD = N_extracted_SD_1960_64,
         N_dif_1960_64_lowCI = GloAv_N_1960_64 - N_extracted_highCI_1960_64,
         N_dif_1960_64_highCI = GloAv_N_1960_64 - N_extracted_lowCI_1960_64,
         N_dif_1960_64_per = (N_dif_1960_64 / N_extracted_1960_64) * 100,
         N_dif_1960_64_per_SD = abs(sqrt((N_dif_1960_64_SD / N_dif_1960_64)^2 + (N_extracted_SD_1960_64 / N_extracted_1960_64)^2) * N_dif_1960_64_per),
         N_dif_1960_64_per_lowCI = (N_dif_1960_64_lowCI / N_extracted_highCI_1960_64) * 100,
         N_dif_1960_64_per_highCI = (N_dif_1960_64_highCI / N_extracted_lowCI_1960_64) * 100,
         
         N_dif_1993_97 = GloAv_N_1993_97 - N_extracted_1993_97,
         N_dif_1993_97_SD = N_extracted_SD_1993_97,
         N_dif_1993_97_lowCI = GloAv_N_1993_97 - N_extracted_highCI_1993_97,
         N_dif_1993_97_highCI = GloAv_N_1993_97 - N_extracted_lowCI_1993_97,
         N_dif_1993_97_per = (N_dif_1993_97 / N_extracted_1993_97) * 100,
         N_dif_1993_97_per_SD = abs(sqrt((N_dif_1993_97_SD / N_dif_1993_97)^2 + (N_extracted_SD_1993_97 / N_extracted_1993_97)^2) * N_dif_1993_97_per),
         N_dif_1993_97_per_lowCI = (N_dif_1993_97_lowCI / N_extracted_highCI_1993_97) * 100,
         N_dif_1993_97_per_highCI = (N_dif_1993_97_highCI / N_extracted_lowCI_1993_97) * 100,
         
         N_dif_2014_18 = GloAv_N_2014_18 - N_extracted_2014_18,
         N_dif_2014_18_SD = N_extracted_SD_2014_18,
         N_dif_2014_18_lowCI = GloAv_N_2014_18 - N_extracted_highCI_2014_18,
         N_dif_2014_18_highCI = GloAv_N_2014_18 - N_extracted_lowCI_2014_18,
         N_dif_2014_18_per = (N_dif_2014_18 / N_extracted_2014_18) * 100,
         N_dif_2014_18_per_SD = abs(sqrt((N_dif_2014_18_SD / N_dif_2014_18)^2 + (N_extracted_SD_2014_18 / N_extracted_2014_18)^2) * N_dif_2014_18_per),
         N_dif_2014_18_per_lowCI = (N_dif_2014_18_lowCI / N_extracted_highCI_2014_18) * 100,
         N_dif_2014_18_per_highCI = (N_dif_2014_18_highCI / N_extracted_lowCI_2014_18) * 100) %>% 
  # Phosphorus
  mutate(P_dif = GloAv_P_extracted - P_extracted,
         P_dif_SD = P_extracted_SD,
         P_dif_lowCI = GloAv_P_extracted - P_extracted_highCI,
         P_dif_highCI = GloAv_P_extracted - P_extracted_lowCI,
         P_dif_per = (P_dif / P_extracted) * 100,
         P_dif_per_SD = abs(sqrt((P_dif_SD / P_dif)^2 + (P_extracted_SD / P_extracted)^2) * P_dif_per),
         P_dif_per_lowCI = (P_dif_lowCI / P_extracted_highCI) * 100,
         P_dif_per_highCI = (P_dif_highCI / P_extracted_lowCI) * 100,
         
         P_dif_1960_64 = GloAv_P_1960_64 - P_extracted_1960_64,
         P_dif_1960_64_SD = P_extracted_SD_1960_64,
         P_dif_1960_64_lowCI = GloAv_P_1960_64 - P_extracted_highCI_1960_64,
         P_dif_1960_64_highCI = GloAv_P_1960_64 - P_extracted_lowCI_1960_64,
         P_dif_1960_64_per = (P_dif_1960_64 / P_extracted_1960_64) * 100,
         P_dif_1960_64_per_SD = abs(sqrt((P_dif_1960_64_SD / P_dif_1960_64)^2 + (P_extracted_SD_1960_64 / P_extracted_1960_64)^2) * P_dif_1960_64_per),
         P_dif_1960_64_per_lowCI = (P_dif_1960_64_lowCI / P_extracted_highCI_1960_64) * 100,
         P_dif_1960_64_per_highCI = (P_dif_1960_64_highCI / P_extracted_lowCI_1960_64) * 100,
         
         P_dif_1993_97 = GloAv_P_1993_97 - P_extracted_1993_97,
         P_dif_1993_97_SD = P_extracted_SD_1993_97,
         P_dif_1993_97_lowCI = GloAv_P_1993_97 - P_extracted_highCI_1993_97,
         P_dif_1993_97_highCI = GloAv_P_1993_97 - P_extracted_lowCI_1993_97,
         P_dif_1993_97_per = (P_dif_1993_97 / P_extracted_1993_97) * 100,
         P_dif_1993_97_per_SD = abs(sqrt((P_dif_1993_97_SD / P_dif_1993_97)^2 + (P_extracted_SD_1993_97 / P_extracted_1993_97)^2) * P_dif_1993_97_per),
         P_dif_1993_97_per_lowCI = (P_dif_1993_97_lowCI / P_extracted_highCI_1993_97) * 100,
         P_dif_1993_97_per_highCI = (P_dif_1993_97_highCI / P_extracted_lowCI_1993_97) * 100,
         
         P_dif_2014_18 = GloAv_P_2014_18 - P_extracted_2014_18,
         P_dif_2014_18_SD = P_extracted_SD_2014_18,
         P_dif_2014_18_lowCI = GloAv_P_2014_18 - P_extracted_highCI_2014_18,
         P_dif_2014_18_highCI = GloAv_P_2014_18 - P_extracted_lowCI_2014_18,
         P_dif_2014_18_per = (P_dif_2014_18 / P_extracted_2014_18) * 100,
         P_dif_2014_18_per_SD = abs(sqrt((P_dif_2014_18_SD / P_dif_2014_18)^2 + (P_extracted_SD_2014_18 / P_extracted_2014_18)^2) * P_dif_2014_18_per),
         P_dif_2014_18_per_lowCI = (P_dif_2014_18_lowCI / P_extracted_highCI_2014_18) * 100,
         P_dif_2014_18_per_highCI = (P_dif_2014_18_highCI / P_extracted_lowCI_2014_18) * 100)








#### PER SIMPLE FUNCTIONAL GROUP ####

# The following code is to produce the global estimates per trophic group.

GloAv_NutrientExtraction_perSFG <- Fisheries_NutrientExtraction %>% group_by(simp_functional_group) %>% 
  filter(year %in% c(1960:2018)) %>% 
  summarize(GloAv_C_extracted = sum(tonnes * 0.125, na.rm = TRUE), 
            GloAv_N_extracted = sum(tonnes * 0.028, na.rm = TRUE), 
            GloAv_P_extracted = sum(tonnes * 0.006, na.rm = TRUE),
            GloAv_C_1960_64 = sum(ifelse(between(year, 1960, 1964),tonnes * 0.125, 0), na.rm = TRUE),
            GloAv_N_1960_64 = sum(ifelse(between(year, 1960, 1964),tonnes * 0.028, 0), na.rm = TRUE), 
            GloAv_P_1960_64 = sum(ifelse(between(year, 1960, 1964),tonnes * 0.006, 0), na.rm = TRUE),
            GloAv_C_1993_97 = sum(ifelse(between(year, 1993, 1997),tonnes * 0.125, 0), na.rm = TRUE),
            GloAv_N_1993_97 = sum(ifelse(between(year, 1993, 1997),tonnes * 0.028, 0), na.rm = TRUE), 
            GloAv_P_1993_97 = sum(ifelse(between(year, 1993, 1997),tonnes * 0.006, 0), na.rm = TRUE),
            GloAv_C_2014_18 = sum(ifelse(between(year, 2014, 2018),tonnes * 0.125, 0), na.rm = TRUE),
            GloAv_N_2014_18 = sum(ifelse(between(year, 2014, 2018),tonnes * 0.028, 0), na.rm = TRUE), 
            GloAv_P_2014_18 = sum(ifelse(between(year, 2014, 2018),tonnes * 0.006, 0), na.rm = TRUE))

GloAv_NutrientExtraction_perSFG <- merge(NutrientExtraction_perSFG, GloAv_NutrientExtraction_perSFG, by = "simp_functional_group",all.x = TRUE)
# Calculate difference between using global averages and our composition estimates. Positive numbers indicate overestimations by global averages, negative numbers indicate underestimations.
GloAv_NutrientExtraction_perSFG <- GloAv_NutrientExtraction_perSFG %>% 
  mutate(C_dif = GloAv_C_extracted - C_extracted,
         C_dif_SD = C_extracted_SD,
         C_dif_lowCI = GloAv_C_extracted - C_extracted_highCI,
         C_dif_highCI = GloAv_C_extracted - C_extracted_lowCI,
         C_dif_per = (C_dif / C_extracted) * 100,
         C_dif_per_SD = abs(sqrt((C_dif_SD / C_dif)^2 + (C_extracted_SD/C_extracted)^2) * C_dif_per),
         C_dif_per_lowCI = (C_dif_lowCI / C_extracted_highCI) * 100,
         C_dif_per_highCI = (C_dif_highCI / C_extracted_lowCI) * 100,
         
         C_dif_1960_64 = GloAv_C_1960_64 - C_extracted_1960_64,
         C_dif_1960_64_SD = C_extracted_SD_1960_64,
         C_dif_1960_64_lowCI = GloAv_C_1960_64 - C_extracted_highCI_1960_64,
         C_dif_1960_64_highCI = GloAv_C_1960_64 - C_extracted_lowCI_1960_64,
         C_dif_1960_64_per = (C_dif_1960_64 / C_extracted_1960_64) * 100,
         C_dif_1960_64_per_SD = abs(sqrt((C_dif_1960_64_SD / C_dif_1960_64)^2 + (C_extracted_SD_1960_64/C_extracted_1960_64)^2) * C_dif_1960_64_per),
         C_dif_1960_64_per_lowCI = (C_dif_1960_64_lowCI / C_extracted_highCI_1960_64) * 100,
         C_dif_1960_64_per_highCI = (C_dif_1960_64_highCI / C_extracted_lowCI_1960_64) * 100,
         
         C_dif_1993_97 = GloAv_C_1993_97 - C_extracted_1993_97,
         C_dif_1993_97_SD = C_extracted_SD_1993_97,
         C_dif_1993_97_lowCI = GloAv_C_1993_97 - C_extracted_highCI_1993_97,
         C_dif_1993_97_highCI = GloAv_C_1993_97 - C_extracted_lowCI_1993_97,
         C_dif_1993_97_per = (C_dif_1993_97 / C_extracted_1993_97) * 100,
         C_dif_1993_97_per_SD = abs(sqrt((C_dif_1993_97_SD / C_dif_1993_97)^2 + (C_extracted_SD_1993_97 / C_extracted_1993_97)^2) * C_dif_1993_97_per),
         C_dif_1993_97_per_lowCI = (C_dif_1993_97_lowCI / C_extracted_highCI_1993_97) * 100,
         C_dif_1993_97_per_highCI = (C_dif_1993_97_highCI / C_extracted_lowCI_1993_97) * 100,
         
         C_dif_2014_18 = GloAv_C_2014_18 - C_extracted_2014_18,
         C_dif_2014_18_SD = C_extracted_SD_2014_18,
         C_dif_2014_18_lowCI = GloAv_C_2014_18 - C_extracted_highCI_2014_18,
         C_dif_2014_18_highCI = GloAv_C_2014_18 - C_extracted_lowCI_2014_18,
         C_dif_2014_18_per = (C_dif_2014_18 / C_extracted_2014_18) * 100,
         C_dif_2014_18_per_SD = abs(sqrt((C_dif_2014_18_SD / C_dif_2014_18)^2 + (C_extracted_SD_2014_18 / C_extracted_2014_18)^2) * C_dif_2014_18_per),
         C_dif_2014_18_per_lowCI = (C_dif_2014_18_lowCI / C_extracted_highCI_2014_18) * 100,
         C_dif_2014_18_per_highCI = (C_dif_2014_18_highCI / C_extracted_lowCI_2014_18) * 100) %>% 
  #Nitrogen
  mutate(N_dif = GloAv_N_extracted - N_extracted,
         N_dif_SD = N_extracted_SD,
         N_dif_lowCI = GloAv_N_extracted - N_extracted_highCI,
         N_dif_highCI = GloAv_N_extracted - N_extracted_lowCI,
         N_dif_per = (N_dif / N_extracted) * 100,
         N_dif_per_SD = abs(sqrt((N_dif_SD / N_dif)^2 + (N_extracted_SD / N_extracted)^2) * N_dif_per),
         N_dif_per_lowCI = (N_dif_lowCI / N_extracted_highCI) * 100,
         N_dif_per_highCI = (N_dif_highCI / N_extracted_lowCI) * 100,
         
         N_dif_1960_64 = GloAv_N_1960_64 - N_extracted_1960_64,
         N_dif_1960_64_SD = N_extracted_SD_1960_64,
         N_dif_1960_64_lowCI = GloAv_N_1960_64 - N_extracted_highCI_1960_64,
         N_dif_1960_64_highCI = GloAv_N_1960_64 - N_extracted_lowCI_1960_64,
         N_dif_1960_64_per = (N_dif_1960_64 / N_extracted_1960_64) * 100,
         N_dif_1960_64_per_SD = abs(sqrt((N_dif_1960_64_SD / N_dif_1960_64)^2 + (N_extracted_SD_1960_64 / N_extracted_1960_64)^2) * N_dif_1960_64_per),
         N_dif_1960_64_per_lowCI = (N_dif_1960_64_lowCI / N_extracted_highCI_1960_64) * 100,
         N_dif_1960_64_per_highCI = (N_dif_1960_64_highCI / N_extracted_lowCI_1960_64) * 100,
         
         N_dif_1993_97 = GloAv_N_1993_97 - N_extracted_1993_97,
         N_dif_1993_97_SD = N_extracted_SD_1993_97,
         N_dif_1993_97_lowCI = GloAv_N_1993_97 - N_extracted_highCI_1993_97,
         N_dif_1993_97_highCI = GloAv_N_1993_97 - N_extracted_lowCI_1993_97,
         N_dif_1993_97_per = (N_dif_1993_97 / N_extracted_1993_97) * 100,
         N_dif_1993_97_per_SD = abs(sqrt((N_dif_1993_97_SD / N_dif_1993_97)^2 + (N_extracted_SD_1993_97 / N_extracted_1993_97)^2) * N_dif_1993_97_per),
         N_dif_1993_97_per_lowCI = (N_dif_1993_97_lowCI / N_extracted_highCI_1993_97) * 100,
         N_dif_1993_97_per_highCI = (N_dif_1993_97_highCI / N_extracted_lowCI_1993_97) * 100,
         
         N_dif_2014_18 = GloAv_N_2014_18 - N_extracted_2014_18,
         N_dif_2014_18_SD = N_extracted_SD_2014_18,
         N_dif_2014_18_lowCI = GloAv_N_2014_18 - N_extracted_highCI_2014_18,
         N_dif_2014_18_highCI = GloAv_N_2014_18 - N_extracted_lowCI_2014_18,
         N_dif_2014_18_per = (N_dif_2014_18 / N_extracted_2014_18) * 100,
         N_dif_2014_18_per_SD = abs(sqrt((N_dif_2014_18_SD / N_dif_2014_18)^2 + (N_extracted_SD_2014_18 / N_extracted_2014_18)^2) * N_dif_2014_18_per),
         N_dif_2014_18_per_lowCI = (N_dif_2014_18_lowCI / N_extracted_highCI_2014_18) * 100,
         N_dif_2014_18_per_highCI = (N_dif_2014_18_highCI / N_extracted_lowCI_2014_18) * 100) %>% 
  # Phosphorus
  mutate(P_dif = GloAv_P_extracted - P_extracted,
         P_dif_SD = P_extracted_SD,
         P_dif_lowCI = GloAv_P_extracted - P_extracted_highCI,
         P_dif_highCI = GloAv_P_extracted - P_extracted_lowCI,
         P_dif_per = (P_dif / P_extracted) * 100,
         P_dif_per_SD = abs(sqrt((P_dif_SD / P_dif)^2 + (P_extracted_SD / P_extracted)^2) * P_dif_per),
         P_dif_per_lowCI = (P_dif_lowCI / P_extracted_highCI) * 100,
         P_dif_per_highCI = (P_dif_highCI / P_extracted_lowCI) * 100,
         
         P_dif_1960_64 = GloAv_P_1960_64 - P_extracted_1960_64,
         P_dif_1960_64_SD = P_extracted_SD_1960_64,
         P_dif_1960_64_lowCI = GloAv_P_1960_64 - P_extracted_highCI_1960_64,
         P_dif_1960_64_highCI = GloAv_P_1960_64 - P_extracted_lowCI_1960_64,
         P_dif_1960_64_per = (P_dif_1960_64 / P_extracted_1960_64) * 100,
         P_dif_1960_64_per_SD = abs(sqrt((P_dif_1960_64_SD / P_dif_1960_64)^2 + (P_extracted_SD_1960_64 / P_extracted_1960_64)^2) * P_dif_1960_64_per),
         P_dif_1960_64_per_lowCI = (P_dif_1960_64_lowCI / P_extracted_highCI_1960_64) * 100,
         P_dif_1960_64_per_highCI = (P_dif_1960_64_highCI / P_extracted_lowCI_1960_64) * 100,
         
         P_dif_1993_97 = GloAv_P_1993_97 - P_extracted_1993_97,
         P_dif_1993_97_SD = P_extracted_SD_1993_97,
         P_dif_1993_97_lowCI = GloAv_P_1993_97 - P_extracted_highCI_1993_97,
         P_dif_1993_97_highCI = GloAv_P_1993_97 - P_extracted_lowCI_1993_97,
         P_dif_1993_97_per = (P_dif_1993_97 / P_extracted_1993_97) * 100,
         P_dif_1993_97_per_SD = abs(sqrt((P_dif_1993_97_SD / P_dif_1993_97)^2 + (P_extracted_SD_1993_97 / P_extracted_1993_97)^2) * P_dif_1993_97_per),
         P_dif_1993_97_per_lowCI = (P_dif_1993_97_lowCI / P_extracted_highCI_1993_97) * 100,
         P_dif_1993_97_per_highCI = (P_dif_1993_97_highCI / P_extracted_lowCI_1993_97) * 100,
         
         P_dif_2014_18 = GloAv_P_2014_18 - P_extracted_2014_18,
         P_dif_2014_18_SD = P_extracted_SD_2014_18,
         P_dif_2014_18_lowCI = GloAv_P_2014_18 - P_extracted_highCI_2014_18,
         P_dif_2014_18_highCI = GloAv_P_2014_18 - P_extracted_lowCI_2014_18,
         P_dif_2014_18_per = (P_dif_2014_18 / P_extracted_2014_18) * 100,
         P_dif_2014_18_per_SD = abs(sqrt((P_dif_2014_18_SD / P_dif_2014_18)^2 + (P_extracted_SD_2014_18 / P_extracted_2014_18)^2) * P_dif_2014_18_per),
         P_dif_2014_18_per_lowCI = (P_dif_2014_18_lowCI / P_extracted_highCI_2014_18) * 100,
         P_dif_2014_18_per_highCI = (P_dif_2014_18_highCI / P_extracted_lowCI_2014_18) * 100)
